services:
  api:
    build: .
    container_name: ocr-api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE=http://ollama:11434
      - INBOX_DIR=/data/inbox
      - OUTBOX_DIR=/data/outbox
      # OPENROUTER_API_KEY should be set via host env if you enable vision
      # OPENROUTER_VISION_MODEL=${OPENROUTER_VISION_MODEL:-qwen2.5-vl-7b-instruct}
    volumes:
      - ./:/app
      - ./data/inbox:/data/inbox
      - ./data/outbox:/data/outbox
      - ./data/config:/data/config
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama:/root/.ollama
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
  watcher:
    build: .
    container_name: ocr-watcher
    command: ["python", "-m", "app.watcher"]
    environment:
      - OLLAMA_BASE=http://ollama:11434
      - INBOX_DIR=/data/inbox
      - OUTBOX_DIR=/data/outbox
      # OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      # OPENROUTER_VISION_MODEL=${OPENROUTER_VISION_MODEL:-qwen2.5-vl-7b-instruct}
    volumes:
      - ./:/app
      - ./data/inbox:/data/inbox
      - ./data/outbox:/data/outbox
      - ./data/config:/data/config
    depends_on:
      - ollama
volumes:
  ollama:
